custom exception and IT for login failure
department-of-veterans-affairs/lighthouse-vistalink pull request #18
Opened 2020-10-30 14:02 UTC by eclendenning-va

2020-10-30 14:48 UTC, ilaflamme-va approved these changes

2020-10-30 16:45 UTC, ilaflamme-va requested changes

2020-10-30 16:45 UTC, ilaflamme-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/VistaLinkExceptions.java
> +  public static final class VistaLoginException extends VistaLinkException {
_VistaLoginFailed_ instead of _VistaLoginException_

2020-10-30 16:45 UTC, ilaflamme-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/VistaLinkExceptions.java
> +public final class VistaLinkExceptions {
No need for final, it's a `@UtilityClass`

2020-10-30 16:45 UTC, ilaflamme-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/VistaLinkExceptions.java
> +public final class VistaLinkExceptions {
`@UtilityClass` marks inner-classes as static.

2020-10-30 16:48 UTC, ilaflamme-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/VistaLinkExceptions.java
> +  static class VistaLinkException extends Exception {
extends _RuntimeException_?

2020-10-30 18:07 UTC, jhulbert-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/WebExceptionHandler.java
> +  public RpcResponse handleFailedLogin(Exception e, HttpServletRequest request) {
Add this to the WEHTest

2020-11-02 14:51 UTC, bschofield-va commented on vistalink/src/main/java/gov/va/api/lighthouse/vistalink/service/controller/ParallelRpcExecutor.java
> +    if (message.contains("VistaLoginModuleTooManyInvalidAttemptsException")) {
I dunno about this... I'm looking for alternatives

2020-11-02 15:03 UTC, ilaflamme-va approved these changes

2020-11-02 15:32 UTC, bschofield-va approved these changes

2020-11-02 15:46 UTC, merged